baseURL = "https://xn--80akpfvdka.xn--p1ai/"
languageCode = "en"
defaultContentLanguage = "en"

googleAnalytics = "G-B0FZEG9NGJ"

title = "SmartDiag - Ваш проводник в мире автодиагностики"
 copyright = "© 2022-2023 SmartDiag"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "SmartDiag"
  headline = "Мы рады приветствовать Вас на нашем сайте"
  image = "logo.png"  # path relative to static directory

  links = [
     { link = { href = "программы/", target = "_self" } },
     { elm = "https://drive.filen.io/f/68e730d7-d91d-4cd3-84ea-b3de9a3d0b15#wMJdF6g7wmNWsdDpjXtnddHe9aeApjME" },
    # { ozon = "https://www.ozon.ru/seller/smart-tech-593268/products/?miniapp=seller_593268" },
    # { yandex = "https://market.yandex.ru/business--smart-tech/17135430" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/smartdiag_robot" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
   { email = { href = "feedback/", text = "Обратная связь", target = "_self" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
